$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/RetroMusicPlayer)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/Browser)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/DotPapers)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/LawnChair)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/SubstratumSignature)
